In [1]:
import pandas as pd
ML_table = pd.read_csv("ML_table_labeled.csv")
ML_table.head(20)

FileNotFoundError: [Errno 2] No such file or directory: 'ML_table_labeled.csv'

In [ ]:
ML_table[ML_table["delivery_status"] == 'late']

In [3]:
len(ML_table[ML_table["delivery_status"] == "late"])

10792

In [4]:
ML_table = ML_table.sort_values("order_purchase_timestamp")
ML_table.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items,total_price,total_freight_value,total_payment,max_installments,payment_count,delivery_status
4541,2e7a8482f6fb09756ca50c10d7bfc047,08c5351a6aca1c1589a38f244edeee9d,shipped,2016-09-04 21:15:19,2016-10-07 13:18:03,2016-10-18 13:14:51,NaN,2016-10-20 00:00:00,2.0,72.89,63.34,136.23,1.0,1.0,late
4396,e5fa5a7210941f7d56d0208e4e071d35,683c54fc24d40ee9f8a6fc179fd9856c,canceled,2016-09-05 00:15:34,2016-10-07 13:17:15,NaN,NaN,2016-10-28 00:00:00,1.0,59.50,15.56,75.06,3.0,1.0,late
10071,809a282bbd5dbcabb6f2f724fca862ec,622e13439d6b5a0b486c435618b2679e,canceled,2016-09-13 15:24:19,2016-10-07 13:16:46,NaN,NaN,2016-09-30 00:00:00,NaN,NaN,NaN,40.95,2.0,1.0,late
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,3.0,134.97,8.49,NaN,NaN,NaN,late
83078,71303d7e93b399f5bcd537d124c0bcfa,b106b360fe2ef8849fbbd056f777b4d5,canceled,2016-10-02 22:07:52,2016-10-06 15:50:56,NaN,NaN,2016-10-25 00:00:00,1.0,100.00,9.34,109.34,1.0,1.0,late

In [5]:
train_data = int(len(ML_table) *0.70)
val_data = int(len(ML_table) * 0.85)
print(train_data)
print(val_data)

69608
84524

In [6]:
train = ML_table.iloc[:train_data]
validation = ML_table.iloc[train_data:val_data]
test = ML_table.iloc[val_data:]

In [7]:
print("Train Data:",train.shape)
print("Validation Data:",validation.shape)
print("Test Data:", test.shape)

Train Data: (69608, 15)
Validation Data: (14916, 15)
Test Data: (14917, 15)

In [8]:
print("Train:")
print(train["delivery_status"].value_counts(normalize = True))
print("\nValidation:")
print(validation["delivery_status"].value_counts(normalize = True))
print("\n Test:")
print(test["delivery_status"].value_counts(normalize = True))

Train:
delivery_status
on time    0.878405
late       0.121595
Name: proportion, dtype: float64

Validation:
delivery_status
on time    0.931081
late       0.068919
Name: proportion, dtype: float64

 Test:
delivery_status
on time    0.912851
late       0.087149
Name: proportion, dtype: float64

In [9]:
print(ML_table["order_purchase_timestamp"].min())
print(ML_table["order_purchase_timestamp"].max())

2016-09-04 21:15:19
2018-10-17 17:30:18

In [10]:
x_train = train.drop(columns=["delivery_status"])
y_train = train["delivery_status"]

x_val = validation.drop(columns=["delivery_status"])
y_val = validation["delivery_status"]

x_test = test.drop(columns=["delivery_status"])
y_test = test["delivery_status"]

In [11]:
print("X_train:", x_train.shape)
print("y_train:", y_train.shape)

print("X_val:", x_val.shape)
print("y_val:", y_val.shape)

print("X_test:", x_test.shape)
print("y_test:", y_test.shape)

X_train: (69608, 14)
y_train: (69608,)
X_val: (14916, 14)
y_val: (14916,)
X_test: (14917, 14)
y_test: (14917,)

In [30]:
train.to_csv("train.csv", index = False)
test.to_csv("test.csv" , index = False)
validation.to_csv("validation.csv" , index = False )

In [13]:
import os
print(os.path.exists("train.csv"))
print(os.path.exists("test.csv"))
print(os.path.exists("validation.csv"))

True
True
True

In [14]:
import pandas as pd 
from sqlalchemy import create_engine
engine = create_engine("postgresql://postgres:1152205@localhost:5432/olist")
tables = pd.read_sql("""SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' """,engine) 
tables

                          table_name
0                          customers
1                         gelocation
2                        order_items
3                     order_payments
4                             orders
5                      order_reviews
6                           products
7  product_category_name_translation
8                            sellers

In [15]:
orders = pd.read_sql("SELECT * FROM orders", engine)
customers = pd.read_sql("SELECT * FROM customers", engine)
order_items = pd.read_sql("Select * FROM order_items", engine)
sellers = pd.read_sql("SELECT * FROM sellers" , engine)
gelocation = pd.read_sql("SELECT * FROM gelocation", engine)

In [18]:
def haversine(lat1, lon1, lat2, lon2):
    
    R = 6371  # Earth radius in kilometers
    
    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)
    
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = (
        np.sin(dlat / 2)**2
        + np.cos(lat1)
        * np.cos(lat2)
        * np.sin(dlon / 2)**2
    )
    
    c = 2 * np.arcsin(np.sqrt(a))
    
    return R * c

In [19]:
import numpy as np

geo_grouped = gelocation.groupby("geolocation_zip_code_prefix")[
    ["geolocation_lat", "geolocation_lng"]
].mean().reset_index()


temp_geo = (
    test[["order_id"]]
    .merge(orders[["order_id", "customer_id"]], on="order_id", how="left")
    .merge(customers[["customer_id", "customer_state", "customer_zip_code_prefix"]], on="customer_id", how="left")
    .merge(order_items[["order_id", "seller_id"]], on="order_id", how="left")
    .merge(sellers[["seller_id", "seller_state", "seller_zip_code_prefix"]], on="seller_id", how="left")
)


temp_geo = temp_geo.merge(
    geo_grouped, left_on="customer_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="left"
).rename(columns={"geolocation_lat": "customer_lat", "geolocation_lng": "customer_lng"})

temp_geo = temp_geo.merge(
    geo_grouped, left_on="seller_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="left"
).rename(columns={"geolocation_lat": "seller_lat", "geolocation_lng": "seller_lng"})

test["customer_state"] = temp_geo["customer_state"]
test["seller_state"] = temp_geo["seller_state"]
test["distance_km"] = haversine(
    temp_geo["customer_lat"], temp_geo["customer_lng"], 
    temp_geo["seller_lat"], temp_geo["seller_lng"]
)

In [20]:
test.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'total_items',
 'total_price',
 'total_freight_value',
 'total_payment',
 'max_installments',
 'payment_count',
 'delivery_status',
 'customer_state',
 'seller_state',
 'distance_km']

In [21]:
test["order_purchase_timestamp"] = pd.to_datetime(
    test["order_purchase_timestamp"]
)

test["month_name"] = test["order_purchase_timestamp"].dt.month_name()

test["day_name"] = test["order_purchase_timestamp"].dt.day_name()

In [22]:
test[[
    "month_name",
    "day_name",
    "customer_state",
    "seller_state",
    "distance_km"
]].head()

      month_name   day_name customer_state seller_state  distance_km
28265       June  Wednesday            NaN          NaN          NaN
19714       June  Wednesday            NaN          NaN          NaN
74857       June  Wednesday            NaN          NaN          NaN
75015       June  Wednesday            NaN          NaN          NaN
723         June  Wednesday             MG           SP   488.536056

In [23]:
test.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'total_items',
 'total_price',
 'total_freight_value',
 'total_payment',
 'max_installments',
 'payment_count',
 'delivery_status',
 'customer_state',
 'seller_state',
 'distance_km',
 'month_name',
 'day_name']

In [27]:

geo_grouped = gelocation.groupby("geolocation_zip_code_prefix")[
    ["geolocation_lat", "geolocation_lng"]
].mean().reset_index()


temp_geo_validation = (
    validation[["order_id"]]
    .merge(orders[["order_id", "customer_id"]], on="order_id", how="left")
    .merge(customers[["customer_id", "customer_state", "customer_zip_code_prefix"]], on="customer_id", how="left")
    .merge(order_items[["order_id", "seller_id"]], on="order_id", how="left")
    .merge(sellers[["seller_id", "seller_state", "seller_zip_code_prefix"]], on="seller_id", how="left")
)


temp_geo_validation = temp_geo_validation.merge(
    geo_grouped, left_on="customer_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="left"
).rename(columns={"geolocation_lat": "customer_lat", "geolocation_lng": "customer_lng"})

temp_geo_validation = temp_geo_validation.merge(
    geo_grouped, left_on="seller_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="left"
).rename(columns={"geolocation_lat": "seller_lat", "geolocation_lng": "seller_lng"})

validation["customer_state"] = temp_geo_validation["customer_state"]
validation["seller_state"] = temp_geo_validation["seller_state"]
validation["distance_km"] = haversine(
    temp_geo_validation["customer_lat"], temp_geo_validation["customer_lng"], 
    temp_geo_validation["seller_lat"], temp_geo_validation["seller_lng"]
)

In [28]:
validation.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'total_items',
 'total_price',
 'total_freight_value',
 'total_payment',
 'max_installments',
 'payment_count',
 'delivery_status',
 'customer_state',
 'seller_state',
 'distance_km',
 'month_name',
 'day_name']

In [29]:
validation["order_purchase_timestamp"] = pd.to_datetime(
    validation["order_purchase_timestamp"]
)

validation["month_name"] = validation["order_purchase_timestamp"].dt.month_name()

validation["day_name"] = validation["order_purchase_timestamp"].dt.day_name()