In [1]:
import pandas as pd
ML_table = pd.read_csv("ML_table_labeled.csv")
ML_table.head(20)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items,total_price,total_freight_value,total_payment,max_installments,payment_count,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,29.99,8.72,38.71,1.0,3.0,on time
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,118.70,22.76,141.46,1.0,1.0,on time
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,159.90,19.22,179.12,3.0,1.0,on time
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,45.00,27.20,72.20,1.0,1.0,on time
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,19.90,8.72,28.62,1.0,1.0,on time
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00,1.0,147.90,27.36,175.26,6.0,1.0,on time
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00,1.0,49.90,16.05,65.95,1.0,1.0,late
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00,1.0,59.99,15.17,75.16,3.0,1.0,on time
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00,1.0,19.90,16.05,35.95,1.0,1.0,on time
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00,1.0,149.99,19.77,169.76,1.0,2.0,on time
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00,2.0,198.00,61.06,259.06,1.0,1.0,on time
11,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08 00:00:00,1.0,98.00,16.13,114.13,1.0,1.0,on time
12,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18 00:00:00,1.0,31.90,18.23,50.13,1.0,1.0,on time
13,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08 00:00:00,1.0,19.90,12.80,32.70,3.0,1.0,on time
14,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21 00:00:00,1.0,38.25,16.11,54.36,1.0,1.0,on time
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04 00:00:00,1.0,132.40,14.05,146.45,10.0,1.0,on time
16,403b97836b0c04a622354cf531062e5f,738b086814c6fcc74b8cc583f8516ee3,delivered,2018-01-02 19:00:43,2018-01-02 19:09:04,2018-01-03 18:19:09,2018-01-20 01:38:59,2018-02-06 00:00:00,1.0,1299.00,77.45,1376.45,10.0,1.0,on time
17,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,delivered,2017-12-26 23:41:31,2017-12-26 23:50:22,2017-12-28 18:33:05,2018-01-08 22:36:36,2018-01-29 00:00:00,1.0,27.99,15.10,43.09,4.0,1.0,on time
18,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11 00:00:00,1.0,17.90,11.85,29.75,1.0,1.0,on time
19,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23 00:00:00,1.0,76.00,16.97,92.97,1.0,3.0,on time

In [2]:
ML_table[ML_table["delivery_status"] == 'late']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items,total_price,total_freight_value,total_payment,max_installments,payment_count,delivery_status
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00,1.0,49.90,16.05,65.95,1.0,1.0,late
20,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28 00:00:00,1.0,109.90,8.96,118.86,1.0,1.0,late
25,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12 00:00:00,1.0,109.90,15.53,125.43,1.0,1.0,late
35,8563039e855156e48fccee4d611a3196,5f16605299d698660e0606f7eae2d2f9,delivered,2018-02-17 15:59:46,2018-02-17 16:15:34,2018-02-20 23:03:56,2018-03-20 00:59:25,2018-03-20 00:00:00,1.0,78.00,28.95,106.95,4.0,1.0,late
41,6ea2f835b4556291ffdc53fa0b3b95e8,c7340080e394356141681bd4c9b8fe31,delivered,2017-11-24 21:27:48,2017-11-25 00:21:09,2017-12-13 21:14:05,2017-12-28 18:59:23,2017-12-21 00:00:00,1.0,339.00,17.12,356.12,10.0,1.0,late
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99397,0fa1fab1d7c1211c824596ed5e111e3c,7f3bd6c94d2daf7b6462d1a894a775b4,delivered,2018-03-13 21:48:57,2018-03-13 22:40:28,2018-03-14 19:27:23,2018-04-05 19:59:49,2018-04-02 00:00:00,1.0,249.90,19.63,269.53,10.0,1.0,late
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00,NaN,NaN,NaN,133.97,1.0,1.0,late
99423,38e9133ce29f6bbe35aed9c3863dce01,ad312389a098ceff46ce92c4595c06d0,delivered,2017-10-12 20:54:11,2017-10-14 03:28:24,2017-10-17 17:04:42,2017-11-21 17:06:59,2017-10-31 00:00:00,1.0,36.90,11.85,48.75,1.0,1.0,late
99425,d692ef54145c9cb3322ec2e5508aa3f4,82ddfcf9438b0cd1117b55ac33184df8,delivered,2018-03-21 19:47:18,2018-03-21 20:05:26,2018-03-22 21:11:58,2018-04-11 00:48:31,2018-04-09 00:00:00,1.0,109.97,36.86,146.83,2.0,1.0,late
99432,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,delivered,2017-12-20 09:52:41,2017-12-20 10:09:52,2017-12-20 20:25:25,2018-01-26 15:45:14,2018-01-18 00:00:00,1.0,55.90,15.14,71.04,1.0,1.0,late

In [3]:
len(ML_table[ML_table["delivery_status"] == "late"])

10792

In [4]:
ML_table = ML_table.sort_values("order_purchase_timestamp")
ML_table.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items,total_price,total_freight_value,total_payment,max_installments,payment_count,delivery_status
4541,2e7a8482f6fb09756ca50c10d7bfc047,08c5351a6aca1c1589a38f244edeee9d,shipped,2016-09-04 21:15:19,2016-10-07 13:18:03,2016-10-18 13:14:51,NaN,2016-10-20 00:00:00,2.0,72.89,63.34,136.23,1.0,1.0,late
4396,e5fa5a7210941f7d56d0208e4e071d35,683c54fc24d40ee9f8a6fc179fd9856c,canceled,2016-09-05 00:15:34,2016-10-07 13:17:15,NaN,NaN,2016-10-28 00:00:00,1.0,59.50,15.56,75.06,3.0,1.0,late
10071,809a282bbd5dbcabb6f2f724fca862ec,622e13439d6b5a0b486c435618b2679e,canceled,2016-09-13 15:24:19,2016-10-07 13:16:46,NaN,NaN,2016-09-30 00:00:00,NaN,NaN,NaN,40.95,2.0,1.0,late
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,3.0,134.97,8.49,NaN,NaN,NaN,late
83078,71303d7e93b399f5bcd537d124c0bcfa,b106b360fe2ef8849fbbd056f777b4d5,canceled,2016-10-02 22:07:52,2016-10-06 15:50:56,NaN,NaN,2016-10-25 00:00:00,1.0,100.00,9.34,109.34,1.0,1.0,late

In [5]:
train_data = int(len(ML_table) *0.70)
val_data = int(len(ML_table) * 0.85)
print(train_data)
print(val_data)

69608
84524

In [6]:
train = ML_table.iloc[:train_data]
validation = ML_table.iloc[train_data:val_data]
test = ML_table.iloc[val_data:]

In [7]:
print("Train Data:",train.shape)
print("Validation Data:",validation.shape)
print("Test Data:", test.shape)

Train Data: (69608, 15)
Validation Data: (14916, 15)
Test Data: (14917, 15)

In [8]:
print("Train:")
print(train["delivery_status"].value_counts(normalize = True))
print("\nValidation:")
print(validation["delivery_status"].value_counts(normalize = True))
print("\n Test:")
print(test["delivery_status"].value_counts(normalize = True))

Train:
delivery_status
on time    0.878405
late       0.121595
Name: proportion, dtype: float64

Validation:
delivery_status
on time    0.931081
late       0.068919
Name: proportion, dtype: float64

 Test:
delivery_status
on time    0.912851
late       0.087149
Name: proportion, dtype: float64

In [9]:
print(ML_table["order_purchase_timestamp"].min())
print(ML_table["order_purchase_timestamp"].max())

2016-09-04 21:15:19
2018-10-17 17:30:18

In [10]:
x_train = train.drop(columns=["delivery_status"])
y_train = train["delivery_status"]

x_val = validation.drop(columns=["delivery_status"])
y_val = validation["delivery_status"]

x_test = test.drop(columns=["delivery_status"])
y_test = test["delivery_status"]

In [11]:
print("X_train:", x_train.shape)
print("y_train:", y_train.shape)

print("X_val:", x_val.shape)
print("y_val:", y_val.shape)

print("X_test:", x_test.shape)
print("y_test:", y_test.shape)

X_train: (69608, 14)
y_train: (69608,)
X_val: (14916, 14)
y_val: (14916,)
X_test: (14917, 14)
y_test: (14917,)

In [30]:
train.to_csv("train.csv", index = False)
test.to_csv("test.csv" , index = False)
validation.to_csv("validation.csv" , index = False )

In [13]:
import os
print(os.path.exists("train.csv"))
print(os.path.exists("test.csv"))
print(os.path.exists("validation.csv"))

True
True
True

In [14]:
import pandas as pd 
from sqlalchemy import create_engine
engine = create_engine("postgresql://postgres:1152205@localhost:5432/olist")
tables = pd.read_sql("""SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' """,engine) 
tables

                          table_name
0                          customers
1                         gelocation
2                        order_items
3                     order_payments
4                             orders
5                      order_reviews
6                           products
7  product_category_name_translation
8                            sellers

In [15]:
orders = pd.read_sql("SELECT * FROM orders", engine)
customers = pd.read_sql("SELECT * FROM customers", engine)
order_items = pd.read_sql("Select * FROM order_items", engine)
sellers = pd.read_sql("SELECT * FROM sellers" , engine)
gelocation = pd.read_sql("SELECT * FROM gelocation", engine)

In [18]:
def haversine(lat1, lon1, lat2, lon2):
    
    R = 6371  # Earth radius in kilometers
    
    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)
    
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = (
        np.sin(dlat / 2)**2
        + np.cos(lat1)
        * np.cos(lat2)
        * np.sin(dlon / 2)**2
    )
    
    c = 2 * np.arcsin(np.sqrt(a))
    
    return R * c

In [19]:
import numpy as np

geo_grouped = gelocation.groupby("geolocation_zip_code_prefix")[
    ["geolocation_lat", "geolocation_lng"]
].mean().reset_index()


temp_geo = (
    test[["order_id"]]
    .merge(orders[["order_id", "customer_id"]], on="order_id", how="left")
    .merge(customers[["customer_id", "customer_state", "customer_zip_code_prefix"]], on="customer_id", how="left")
    .merge(order_items[["order_id", "seller_id"]], on="order_id", how="left")
    .merge(sellers[["seller_id", "seller_state", "seller_zip_code_prefix"]], on="seller_id", how="left")
)


temp_geo = temp_geo.merge(
    geo_grouped, left_on="customer_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="left"
).rename(columns={"geolocation_lat": "customer_lat", "geolocation_lng": "customer_lng"})

temp_geo = temp_geo.merge(
    geo_grouped, left_on="seller_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="left"
).rename(columns={"geolocation_lat": "seller_lat", "geolocation_lng": "seller_lng"})

test["customer_state"] = temp_geo["customer_state"]
test["seller_state"] = temp_geo["seller_state"]
test["distance_km"] = haversine(
    temp_geo["customer_lat"], temp_geo["customer_lng"], 
    temp_geo["seller_lat"], temp_geo["seller_lng"]
)

In [20]:
test.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'total_items',
 'total_price',
 'total_freight_value',
 'total_payment',
 'max_installments',
 'payment_count',
 'delivery_status',
 'customer_state',
 'seller_state',
 'distance_km']

In [21]:
test["order_purchase_timestamp"] = pd.to_datetime(
    test["order_purchase_timestamp"]
)

test["month_name"] = test["order_purchase_timestamp"].dt.month_name()

test["day_name"] = test["order_purchase_timestamp"].dt.day_name()

In [22]:
test[[
    "month_name",
    "day_name",
    "customer_state",
    "seller_state",
    "distance_km"
]].head()

      month_name   day_name customer_state seller_state  distance_km
28265       June  Wednesday            NaN          NaN          NaN
19714       June  Wednesday            NaN          NaN          NaN
74857       June  Wednesday            NaN          NaN          NaN
75015       June  Wednesday            NaN          NaN          NaN
723         June  Wednesday             MG           SP   488.536056

In [23]:
test.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'total_items',
 'total_price',
 'total_freight_value',
 'total_payment',
 'max_installments',
 'payment_count',
 'delivery_status',
 'customer_state',
 'seller_state',
 'distance_km',
 'month_name',
 'day_name']

In [27]:
import numpy as np


geo_grouped = gelocation.groupby("geolocation_zip_code_prefix")[
    ["geolocation_lat", "geolocation_lng"]
].mean().reset_index()


temp_geo_validation = (
    validation[["order_id"]]
    .merge(orders[["order_id", "customer_id"]], on="order_id", how="left")
    .merge(customers[["customer_id", "customer_state", "customer_zip_code_prefix"]], on="customer_id", how="left")
    .merge(order_items[["order_id", "seller_id"]], on="order_id", how="left")
    .merge(sellers[["seller_id", "seller_state", "seller_zip_code_prefix"]], on="seller_id", how="left")
)


temp_geo_validation = temp_geo_validation.merge(
    geo_grouped, left_on="customer_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="left"
).rename(columns={"geolocation_lat": "customer_lat", "geolocation_lng": "customer_lng"})

temp_geo_validation = temp_geo_validation.merge(
    geo_grouped, left_on="seller_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="left"
).rename(columns={"geolocation_lat": "seller_lat", "geolocation_lng": "seller_lng"})

validation["customer_state"] = temp_geo_validation["customer_state"]
validation["seller_state"] = temp_geo_validation["seller_state"]
validation["distance_km"] = haversine(
    temp_geo_validation["customer_lat"], temp_geo_validation["customer_lng"], 
    temp_geo_validation["seller_lat"], temp_geo_validation["seller_lng"]
)

In [28]:
validation.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'total_items',
 'total_price',
 'total_freight_value',
 'total_payment',
 'max_installments',
 'payment_count',
 'delivery_status',
 'customer_state',
 'seller_state',
 'distance_km',
 'month_name',
 'day_name']

In [29]:
validation["order_purchase_timestamp"] = pd.to_datetime(
    validation["order_purchase_timestamp"]
)

validation["month_name"] = validation["order_purchase_timestamp"].dt.month_name()

validation["day_name"] = validation["order_purchase_timestamp"].dt.day_name()